vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        menu:
            uri_prefix: /images/menu
            upload_destination: '%kernel.project_dir%/public/images/menu'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true